spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sorascm_db
    username: sorascm_app
    password: sorascm_secure_dev_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 7

server:
  port: 8082